from __future__ import annotations

from enum import StrEnum


class ErrorCode(StrEnum):
    INVALID_REQUEST = "INVALID_REQUEST"
    SCHEMA_MISMATCH = "SCHEMA_MISMATCH"
    INTERFACE_VERSION_UNSUPPORTED = "INTERFACE_VERSION_UNSUPPORTED"
    ARTIFACT_MISSING = "ARTIFACT_MISSING"
    ARTIFACT_HASH_MISMATCH = "ARTIFACT_HASH_MISMATCH"
    PATH_OUTSIDE_WORKSPACE = "PATH_OUTSIDE_WORKSPACE"
    ROUTING_POLICY_VIOLATION = "ROUTING_POLICY_VIOLATION"
    CAPABILITY_UNAVAILABLE = "CAPABILITY_UNAVAILABLE"
    TOOL_NOT_IMPLEMENTED = "TOOL_NOT_IMPLEMENTED"
    TOOL_TIMEOUT = "TOOL_TIMEOUT"
    TOOL_CRASHED = "TOOL_CRASHED"
    RESOURCE_EXHAUSTED = "RESOURCE_EXHAUSTED"
    STALE_RTL_VERSION = "STALE_RTL_VERSION"
    MODEL_CONFIG_MISSING = "MODEL_CONFIG_MISSING"
    MODEL_CALL_FAILED = "MODEL_CALL_FAILED"
    GATE2_REQUIRED = "GATE2_REQUIRED"
    A1_COMPILE_FAILED = "A1_COMPILE_FAILED"
    A1_SIMULATION_FAILED = "A1_SIMULATION_FAILED"
    A1_COVERAGE_UNSUPPORTED = "A1_COVERAGE_UNSUPPORTED"
    A1_PROFILE_INCOMPLETE = "A1_PROFILE_INCOMPLETE"
    A2_PROTOCOL_UNRESOLVED = "A2_PROTOCOL_UNRESOLVED"
    A2_REFERENCE_MODEL_MISSING = "A2_REFERENCE_MODEL_MISSING"
    A2_COVERAGE_MODEL_INVALID = "A2_COVERAGE_MODEL_INVALID"
    A2_TEST_GENERATION_FAILED = "A2_TEST_GENERATION_FAILED"
    A3_AIG_BUILD_FAILED = "A3_AIG_BUILD_FAILED"
    A3_EQUIVALENCE_FAILED = "A3_EQUIVALENCE_FAILED"
    A3_MAPPING_FAILED = "A3_MAPPING_FAILED"
    A3_TIMING_ESTIMATION_FAILED = "A3_TIMING_ESTIMATION_FAILED"
    A3_SEARCH_EXHAUSTED = "A3_SEARCH_EXHAUSTED"


class DoorAgentError(RuntimeError):
    def __init__(self, code: ErrorCode, message: str):
        self.code = code
        super().__init__(f"{code}: {message}")
